DROP DATABASE IF EXISTS charityDB;
CREATE DATABASE charityDB;
SHOW DATABASES;

DROP USER jee8webapp@localhost;
CREATE USER jee8webapp@localhost IDENTIFIED BY 'password1';
SELECT user FROM mysql.user;
GRANT ALL PRIVILEGES ON charityDB.* TO jee8webapp@localhost;
FLUSH PRIVILEGES;
SHOW GRANTS FOR jee8webapp@localhost;

SELECT user, host FROM mysql.user;


DROP TABLE IF EXISTS charitydb.CHARITY;

CREATE TABLE charitydb.CHARITY
(
`CHARITY_ID`               MEDIUMINT    NOT NULL AUTO_INCREMENT,
`CHARITY_TAX_ID`           VARCHAR(250) NOT NULL UNIQUE , -- https://tax.co.za/what-is-my-tax-number/
`CHARITY_NAME`             VARCHAR(250),
`CHARITY_MISSION`          VARCHAR(250),
`CHARITY_WEB_ADDRESS`      VARCHAR(250),          -- Need a separate ADDRESS Table
`CHARITY_FACEBOOK_ADDRESS` VARCHAR(250),          -- Need a separate ADDRESS Table
`CHARITY_TWITTER_ADDRESS`  VARCHAR(250),          -- Need a separate ADDRESS Table
PRIMARY KEY (`CHARITY_ID`)
) ENGINE = InnoDB;

CREATE UNIQUE INDEX `PK_CHARITY` ON charitydb.CHARITY (`CHARITY_ID` ASC);


DROP TABLE IF EXISTS charitydb.`CATEGORY`;

CREATE TABLE charitydb.`CATEGORY`
(
`CATEGORY_ID`   MEDIUMINT NOT NULL AUTO_INCREMENT,
`CATEGORY_NAME` VARCHAR(50),
CONSTRAINT `CATEGORY_PK` PRIMARY KEY (`CATEGORY_ID`)
) ENGINE = InnoDB;

CREATE UNIQUE INDEX `IDX_CATEGORY` ON charitydb.`CATEGORY` (`CATEGORY_ID` ASC);

INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('ANIMALS');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('ARTS,CULTURE,HUMANITIES');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('COMMUNITY DEVELOPMENT');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('EDUCATION');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('ENVIRONMENT');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('HEALTH');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('HUMAN SERVICES');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('HUMAN AND CIVIL RIGHTS');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('RELIGION');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('RESEARCH AND PUBLIC POLICY');

DROP TABLE IF EXISTS charitydb.`CHARITY_CATEGORY`;

CREATE TABLE charitydb.`CHARITY_CATEGORY`
(
`CHARITY_ID`  MEDIUMINT NOT NULL,
`CATEGORY_ID` MEDIUMINT NOT NULL
) ENGINE = InnoDB;

ALTER TABLE charitydb.`CHARITY_CATEGORY`
ADD CONSTRAINT `FK_CHARITY_ID`
FOREIGN KEY (CHARITY_ID) REFERENCES charity(CHARITY_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE charitydb.`CHARITY_CATEGORY`
ADD CONSTRAINT `FK_CATEGORY_ID`
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;


DROP TABLE IF EXISTS charitydb.`PROGRAM`;

CREATE TABLE charitydb.`PROGRAM`
(
`PROGRAM_ID`   MEDIUMINT NOT NULL AUTO_INCREMENT,
`PROGRAM_DESCRIPTION` VARCHAR(250),
CONSTRAINT `PROGRAM_PK` PRIMARY KEY (`PROGRAM_ID`)
) ENGINE = InnoDB;

CREATE UNIQUE INDEX `IDX_PROGRAM` ON charitydb.`PROGRAM` (`PROGRAM_ID` ASC);

INSERT INTO PROGRAM (PROGRAM_DESCRIPTION) VALUES ('Residential facility');
INSERT INTO PROGRAM (PROGRAM_DESCRIPTION) VALUES ('Social Work offices for psycho-social services');
INSERT INTO PROGRAM (PROGRAM_DESCRIPTION) VALUES ('Protective workshops');
INSERT INTO PROGRAM (PROGRAM_DESCRIPTION) VALUES ('Home based care');
INSERT INTO PROGRAM (PROGRAM_DESCRIPTION) VALUES ('Pre school');
INSERT INTO PROGRAM (PROGRAM_DESCRIPTION) VALUES ('Orphanage');

DROP TABLE IF EXISTS charitydb.`CHARITY_PROGRAM`;

CREATE TABLE charitydb.`CHARITY_PROGRAM`
(
`CHARITY_ID`  MEDIUMINT NOT NULL,
`PROGRAM_ID` MEDIUMINT NOT NULL
);

ALTER TABLE charitydb.`CHARITY_PROGRAM`
ADD CONSTRAINT `FK_CHARITY_PROGRAM_ID`
FOREIGN KEY (CHARITY_ID) REFERENCES charity(CHARITY_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE charitydb.`CHARITY_PROGRAM`
ADD CONSTRAINT `FK_PROGRAM_ID`
FOREIGN KEY (PROGRAM_ID) REFERENCES program(PROGRAM_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;




